# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Richard Chao
tagline:          'Work hard. Have fun. Make history.'
description:      'M.E.T. @ UC Berkeley'
url:              http://rqchao.github.io
baseurl:          /

author:
  name:           'Richard Chao'
  url:            https://github.com/rqchao

paginate:         5

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
